import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analyzeRouter from "./analyze";
import tidesRouter from "./tides";
import forecastRouter from "./forecast";
import barraRouter from "./barra";
import narrateRouter from "./narrate";
import ttsRouter from "./tts";
import demosRouter from "./demos";
import lureSearchRouter from "./lureSearch";
import dataStatusRouter from "./dataStatus";
import communityRouter from "./community";
import brainRouter from "./brain";
import fishidRouter from "./fishid";
import barracheckRouter from "./barracheck";
import barralibraryRouter from "./barralibrary";
import sonarbarracheckRouter from "./sonarbarracheck";
import sonarbrainRouter from "./sonarbrain";
import crocbrainRouter from "./crocbrain";
import sonarvalidateRouter from "./sonarvalidate";
import insta360surfaceRouter from "./insta360surface";
import insta360crocRouter from "./insta360croc";

const router: IRouter = Router();

router.use(healthRouter);
router.use(analyzeRouter);
router.use(tidesRouter);
router.use(forecastRouter);
router.use(barraRouter);
router.use(narrateRouter);
router.use(ttsRouter);
router.use(demosRouter);
router.use(lureSearchRouter);
router.use(dataStatusRouter);
router.use(communityRouter);
router.use(brainRouter);
router.use(fishidRouter);
router.use(barracheckRouter);
router.use(barralibraryRouter);
router.use(sonarbarracheckRouter);
router.use(sonarbrainRouter);
router.use(crocbrainRouter);
router.use(sonarvalidateRouter);
router.use(insta360surfaceRouter);
router.use(insta360crocRouter);

export default router;
