kind = "mobile"
previewPath = "/hookvision-nt/"
title = "HookVision NT"
version = "1.0.0"
id = "artifacts/hookvision-nt"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/hookvision-nt" ]
localPort = 25353

[services.development]
run = "pnpm --filter @workspace/hookvision-nt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hookvision-nt", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/hookvision-nt", "run", "serve" ]

[services.env]
PORT = "25353"
BASE_PATH = "/hookvision-nt"
