// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/livetrial/LiveTrial.tsx": () => import("../components/mockups/livetrial/LiveTrial.tsx"),
  "./components/mockups/smartlife/SmartLifeDemo.tsx": () => import("../components/mockups/smartlife/SmartLifeDemo.tsx")
};
